### ISSUE TITLE
[feature] coverage nestjs-tinkoff with tests

### ISSUE THREAD

**Issue by tuogeniy** [Atlantis-Lab/nestjs#161]
### С чем связан запрос на фичу?
необходимость в покрытии тестами

### Расскажите как вы это себе видите
1. Создать папку tests
2. Создать файл в котором протестировать https://github.com/Atlantis-Lab/nestjs/blob/master/packages/nestjs-tinkoff/src/guards/request-verifier.guard.ts
Моки для теста можно взять из тестов репозитория https://github.com/Atlantis-Lab/tinkoff-api

**Comment by tuogeniy** [comment]
При старте тестов выходит ошибка как в этом ижью https://github.com/nestjs/nest/issues/2190
Скорее всего проблема в actl-test -> ts-jest

**Comment by TorinAsakura** [comment]
> При старте тестов выходит ошибка как в этом ижью https://github.com/nestjs/nest/issues/2190
> 
> Скорее всего проблема в actl-test -> ts-jest 

И? Дальше-то что? У наших тестов в первой итерации в соседних пакетах всё ок

**Comment by tuogeniy** [comment]
@TorinAsakura значит код в соседний пакетах способен работать на es5. Этот не может

**Comment by TorinAsakura** [comment]
@tuogeniy Решение?

**Comment by tuogeniy** [comment]
@TorinAsakura нужно зависимости пакетов actl, он блочит

**Comment by tuogeniy** [comment]
лог ошибки

tuogeniy@mac nestjs % yarn run test
yarn run v1.22.10
$ mctl test
ts-jest[versions] (WARN) Version 24.9.0 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=26.0.0 <27.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
ts-jest[versions] (WARN) Version 24.9.0 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=26.0.0 <27.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
ts-jest[versions] (WARN) Version 24.9.0 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=26.0.0 <27.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
 PASS  packages/nestjs-map-errors-interceptor/__tests__/interceptor.test.ts (5.611s)
 PASS  packages/server-scripts/__tests__/create-webpack-config.test.ts (6.558s)
 PASS  packages/nestjs-signed-url/__tests__/generate-url.test.ts (6.687s)
 FAIL  packages/nestjs-tinkoff/__tests__/request-verifier-guard.test.ts (18.06s)
  ● Guards › should prevent access (unauthorized)

    TypeError: Class constructor Tinkoff cannot be invoked without 'new'

       8 | export class TinkoffService extends Tinkoff {
       9 |   public constructor(@Inject(TINKOFF_API_OPTIONS) options: TinkoffPublicOptions) {
    > 10 |     super(options)
         |     ^
      11 |   }
      12 | }
      13 | 

      at new TinkoffService (packages/nestjs-tinkoff/src/services/tinkoff.service.ts:10:5)
      at Injector.instantiateClass (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:290:19)
      at callback (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:77:41)
      at Injector.resolveConstructorParams (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:118:24)
      at Injector.loadInstance (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:81:9)
      at Injector.loadProvider (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:38:9)
      at Injector.lookupComponentInImports (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:224:17)
      at Injector.lookupComponentInParentModules (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:190:33)
      at Injector.resolveComponentInstance (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:148:33)
      at resolveParam (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:102:38)
          at async Promise.all (index 0)
      at Injector.resolveConstructorParams (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:117:27)
      at Injector.loadInstance (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:81:9)
      at Injector.loadProvider (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/injector.js:38:9)
          at async Promise.all (index 3)
      at InstanceLoader.createInstancesOfProviders (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/instance-loader.js:43:9)
      at node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/instance-loader.js:28:13
          at async Promise.all (index 1)
      at InstanceLoader.createInstances (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/instance-loader.js:27:9)
      at InstanceLoader.createInstancesOfDependencies (node_modules/@nestjs/testing/node_modules/@nestjs/core/injector/instance-loader.js:17:9)
      at TestingModuleBuilder.compile (node_modules/@nestjs/testing/testing-module.builder.js:43:9)

**Comment by TorinAsakura** [comment]
@tuogeniy это проблема твоего гавнокода, а не проблема mctl или зависимостей

**Comment by tuogeniy** [comment]
@TorinAsakura почему? Код работает

**Comment by TorinAsakura** [comment]
@tuogeniy Потому что твоя ошибка никак не связана с инструментами тестирования. Они в порядке. Всё, что WARN != ERROR

**Comment by tuogeniy** [comment]
@TorinAsakura когда я запускаю тест через jest
```
yarn workspace @atlantis-lab/nestjs-tinkoff run jest
```
этой проблемы нет

**Comment by TorinAsakura** [comment]
> @TorinAsakura когда я запускаю тест через jest
> 
> ```
> yarn workspace @atlantis-lab/nestjs-tinkoff run jest
> ```
> 
> этой проблемы нет

Сейчас закину пакет, попробуй с ним протестить, ток дебагер включи
